management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      CIRCUIT_BREAKER_1:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      RETRY_1:
        maxRetryAttempts: 5
        waitDuration: 3s
  ratelimiter:
    instances:
      RATE_LIMITER_1:
        limitForPeriod: 5 # Số lượng yêu cầu tối đa trong mỗi khoảng thời gian
        limitRefreshPeriod: 60s # Khoảng thời gian reset lại số lượng yêu cầu
        timeoutDuration: 0 # Thời gian chờ trước khi ném ra lỗi nếu bị giới hạn
  timelimiter:
    instances:
      TIME_LIMITER_1:
        timeoutDuration: 2000
        cancelRunningFuture: true