server:
  port: 8080
spring:
  application:
    name: service-apigateway
  cloud:
    gateway:
      routes:
        - id: service_authentication
          uri: http://localhost:8081
          predicates:
            - Path=/authentication/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders: '*'
              maxAge: 3600
            
        - id: service_phone
          uri: http://localhost:8082
          predicates:
            - Path=/phone/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders: '*'
              maxAge: 3600
            
        - id: service_order
          uri: http://localhost:8083
          predicates:
            - Path=/order/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders: '*'
              maxAge: 3600
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/